package hub

type RouterGroup struct {
	// Code generated by github.com/flipped-aurora/gin-vue-admin/server Begin; DO NOT EDIT.

	ZoneRouter
	ZoneGroupRouter
	SiteRouter
	AreaRouter
	CenterRouter
	SiteDeviceMapRouter
	// Code generated by github.com/flipped-aurora/gin-vue-admin/server End; DO NOT EDIT.
	GatwayDeviceTreeRouter
}
