package hub

type ApiGroup struct {
	// Code generated by github.com/flipped-aurora/gin-vue-admin/server Begin; DO NOT EDIT.

	ZoneApi
	ZoneGroupApi
	SiteApi
	AreaApi
	CenterApi
	SiteDeviceMapApi
	// Code generated by github.com/flipped-aurora/gin-vue-admin/server End; DO NOT EDIT.
	GatewayDeviceTreeApi
}
