package hub

type ServiceGroup struct {
	// Code generated by github.com/flipped-aurora/gin-vue-admin/server Begin; DO NOT EDIT.

	ZoneService
	ZoneGroupService
	SiteService
	AreaService
	CenterService
	SiteDeviceMapService
	// Code generated by github.com/flipped-aurora/gin-vue-admin/server End; DO NOT EDIT.
	GatewayDeviceTreeService
	LivePointService
}
